CREATE TABLE USERS(
  USERNAME VARCHAR(50) PRIMARY KEY,
  PASSWORD VARCHAR(50),
  NICKNAME VARCHAR(50),
  EMAIL VARCHAR(50)
);

CREATE TABLE USERS(
  USERNAME VARCHAR(50) PRIMARY KEY,
  EMAIL VARCHAR(50) UNIQUE,
  CAPTCHA VARCHAR(50),
  getTime DATETIME
);